### ISSUE TITLE
Requirements to run docker incl. data gathering and processing?

### ISSUE THREAD

**Issue by k00ni** [k00ni/lodstats.docker#4]
From the discussion below:

> The RAM is an issue and you will need at least 20+ GB for big datasets. Currently LODStats is running on 128 GB machine with 40 cores (akswnc9), the complete evaluation took half a day on that machine (without parallel processing).

**Comment by k00ni** [comment]
@earthquakesan, @GeorgesAlkhouri: Does anyone know which disc space requirements (and maybe RAM and CPU?) need the whole infrastructure to setup? I plan to roll out a test setup on our server to evaluate our latest updates.

**Comment by GeorgesAlkhouri** [comment]
I think RAM should not be an issue, because the datasets are processed over a queue and thus not all data is loaded simultaneously.

**Comment by earthquakesan** [comment]
@k00ni sorry for late answer, was on sick leave

The RAM is an issue and you will need at least 20+ GB for big datasets. Currently LODStats is running on 128 GB machine with 40 cores (akswnc9), the complete evaluation took half a day on that machine (without parallel processing).

**Comment by k00ni** [comment]
@earthquakesan: is there a way to configure the setup or change some files, to be able to *test* it on a local machine? How much disk space is required to run all *required* processes?

**Comment by earthquakesan** [comment]
Sure, you can run it with 4-8 GB RAM, no need to change anything, just start up docker-compose up.

**Comment by earthquakesan** [comment]
I do not have precise requirements for running LODStats at a hand, you need to measure those if you want to know exactly.

**Comment by k00ni** [comment]
> the complete evaluation took half a day on that machine (**without parallel processing**).

@earthquakesan: Did you mean that the queue (rabitmq) isn't used and the whole process is serial? 

If there is no usage of the queue, we aren't able to improve performance by using parallal processing, aren't we?

**Comment by earthquakesan** [comment]
It is used, however I was running only 1 worker because that machine is shared with another projects (i.e. running websites etc).
